[workspace]
members = [
    "examples",
    "ash",
    "ash-window",
    "generator",
]

[patch.crates-io]
vk-parse = { path = "../vk-parse/vk-parse", features = ["vkxml-convert"] }
vkxml = { path = "../vkxml/" }